package com.maxcom.mpm.model;
// Generated 05-sep-2014 15:58:10 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmCestados generated by hbm2java
 */
public class MpmCestados  implements java.io.Serializable {


     private String idEstado;
     private MpmCnotificaciones mpmCnotificaciones;
     private String descripcion;
     private String nombre;
     private Boolean estadoFinal;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private boolean activo;
     private Set<MpmTcobranzaSap> mpmTcobranzaSaps = new HashSet<MpmTcobranzaSap>(0);
     private Set<MpmTprocesos> mpmTprocesoses = new HashSet<MpmTprocesos>(0);
     private Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas = new HashSet<MpmTcobranzaSapDeta>(0);
     private Set<MpmTlotesCargoAutomatico> mpmTlotesCargoAutomaticos = new HashSet<MpmTlotesCargoAutomatico>(0);

    public MpmCestados() {
    }

	
    public MpmCestados(String idEstado, String descripcion, String creadoPor, Date fechaCreacion, String sistema, boolean activo) {
        this.idEstado = idEstado;
        this.descripcion = descripcion;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
        this.activo = activo;
    }
    public MpmCestados(String idEstado, MpmCnotificaciones mpmCnotificaciones, String descripcion, String nombre, Boolean estadoFinal, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, boolean activo, Set<MpmTcobranzaSap> mpmTcobranzaSaps, Set<MpmTprocesos> mpmTprocesoses, Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas, Set<MpmTlotesCargoAutomatico> mpmTlotesCargoAutomaticos) {
       this.idEstado = idEstado;
       this.mpmCnotificaciones = mpmCnotificaciones;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.estadoFinal = estadoFinal;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.mpmTcobranzaSaps = mpmTcobranzaSaps;
       this.mpmTprocesoses = mpmTprocesoses;
       this.mpmTcobranzaSapDetas = mpmTcobranzaSapDetas;
       this.mpmTlotesCargoAutomaticos = mpmTlotesCargoAutomaticos;
    }
   
    public String getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(String idEstado) {
        this.idEstado = idEstado;
    }
    public MpmCnotificaciones getMpmCnotificaciones() {
        return this.mpmCnotificaciones;
    }
    
    public void setMpmCnotificaciones(MpmCnotificaciones mpmCnotificaciones) {
        this.mpmCnotificaciones = mpmCnotificaciones;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Boolean getEstadoFinal() {
        return this.estadoFinal;
    }
    
    public void setEstadoFinal(Boolean estadoFinal) {
        this.estadoFinal = estadoFinal;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<MpmTcobranzaSap> getMpmTcobranzaSaps() {
        return this.mpmTcobranzaSaps;
    }
    
    public void setMpmTcobranzaSaps(Set<MpmTcobranzaSap> mpmTcobranzaSaps) {
        this.mpmTcobranzaSaps = mpmTcobranzaSaps;
    }
    public Set<MpmTprocesos> getMpmTprocesoses() {
        return this.mpmTprocesoses;
    }
    
    public void setMpmTprocesoses(Set<MpmTprocesos> mpmTprocesoses) {
        this.mpmTprocesoses = mpmTprocesoses;
    }
    public Set<MpmTcobranzaSapDeta> getMpmTcobranzaSapDetas() {
        return this.mpmTcobranzaSapDetas;
    }
    
    public void setMpmTcobranzaSapDetas(Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas) {
        this.mpmTcobranzaSapDetas = mpmTcobranzaSapDetas;
    }
    public Set<MpmTlotesCargoAutomatico> getMpmTlotesCargoAutomaticos() {
        return this.mpmTlotesCargoAutomaticos;
    }
    
    public void setMpmTlotesCargoAutomaticos(Set<MpmTlotesCargoAutomatico> mpmTlotesCargoAutomaticos) {
        this.mpmTlotesCargoAutomaticos = mpmTlotesCargoAutomaticos;
    }




}


