package com.maxcom.mpm.model;
// Generated 05-sep-2014 15:58:10 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmCtiposNotificaciones generated by hbm2java
 */
public class MpmCtiposNotificaciones  implements java.io.Serializable {


     private long idTipoNotificacion;
     private String prefijo;
     private String postfijo;
     private String descripcion;
     private String tipoMail;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private boolean activo;
     private Set<MpmCnotificaciones> mpmCnotificacioneses = new HashSet<MpmCnotificaciones>(0);

    public MpmCtiposNotificaciones() {
    }

	
    public MpmCtiposNotificaciones(long idTipoNotificacion, String descripcion, String creadoPor, Date fechaCreacion, String sistema, boolean activo) {
        this.idTipoNotificacion = idTipoNotificacion;
        this.descripcion = descripcion;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
        this.activo = activo;
    }
    public MpmCtiposNotificaciones(long idTipoNotificacion, String prefijo, String postfijo, String descripcion, String tipoMail, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, boolean activo, Set<MpmCnotificaciones> mpmCnotificacioneses) {
       this.idTipoNotificacion = idTipoNotificacion;
       this.prefijo = prefijo;
       this.postfijo = postfijo;
       this.descripcion = descripcion;
       this.tipoMail = tipoMail;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.mpmCnotificacioneses = mpmCnotificacioneses;
    }
   
    public long getIdTipoNotificacion() {
        return this.idTipoNotificacion;
    }
    
    public void setIdTipoNotificacion(long idTipoNotificacion) {
        this.idTipoNotificacion = idTipoNotificacion;
    }
    public String getPrefijo() {
        return this.prefijo;
    }
    
    public void setPrefijo(String prefijo) {
        this.prefijo = prefijo;
    }
    public String getPostfijo() {
        return this.postfijo;
    }
    
    public void setPostfijo(String postfijo) {
        this.postfijo = postfijo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipoMail() {
        return this.tipoMail;
    }
    
    public void setTipoMail(String tipoMail) {
        this.tipoMail = tipoMail;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<MpmCnotificaciones> getMpmCnotificacioneses() {
        return this.mpmCnotificacioneses;
    }
    
    public void setMpmCnotificacioneses(Set<MpmCnotificaciones> mpmCnotificacioneses) {
        this.mpmCnotificacioneses = mpmCnotificacioneses;
    }




}


