package com.maxcom.mpm.model;
// Generated 18-sep-2014 9:04:00 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmCtiposRespuestas generated by hbm2java
 */
public class MpmCtiposRespuestas  implements java.io.Serializable {


     private long idTipoRespuesta;
     private String siglas;
     private String descripcion;
     private Boolean reintento;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private boolean activo;
     private Set<MpmCrespuestasCargos> mpmCrespuestasCargoses = new HashSet<MpmCrespuestasCargos>(0);

    public MpmCtiposRespuestas() {
    }

	
    public MpmCtiposRespuestas(long idTipoRespuesta, String siglas, String descripcion, String creadoPor, Date fechaCreacion, String sistema, boolean activo) {
        this.idTipoRespuesta = idTipoRespuesta;
        this.siglas = siglas;
        this.descripcion = descripcion;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
        this.activo = activo;
    }
    public MpmCtiposRespuestas(long idTipoRespuesta, String siglas, String descripcion, Boolean reintento, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, boolean activo, Set<MpmCrespuestasCargos> mpmCrespuestasCargoses) {
       this.idTipoRespuesta = idTipoRespuesta;
       this.siglas = siglas;
       this.descripcion = descripcion;
       this.reintento = reintento;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.mpmCrespuestasCargoses = mpmCrespuestasCargoses;
    }
   
    public long getIdTipoRespuesta() {
        return this.idTipoRespuesta;
    }
    
    public void setIdTipoRespuesta(long idTipoRespuesta) {
        this.idTipoRespuesta = idTipoRespuesta;
    }
    public String getSiglas() {
        return this.siglas;
    }
    
    public void setSiglas(String siglas) {
        this.siglas = siglas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getReintento() {
        return this.reintento;
    }
    
    public void setReintento(Boolean reintento) {
        this.reintento = reintento;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<MpmCrespuestasCargos> getMpmCrespuestasCargoses() {
        return this.mpmCrespuestasCargoses;
    }
    
    public void setMpmCrespuestasCargoses(Set<MpmCrespuestasCargos> mpmCrespuestasCargoses) {
        this.mpmCrespuestasCargoses = mpmCrespuestasCargoses;
    }




}


