package com.maxcom.mpm.model;
// Generated 18-sep-2014 9:04:00 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmCestados generated by hbm2java
 */
public class MpmCestados  implements java.io.Serializable {


     private String idEstado;
     private MpmCnotificaciones mpmCnotificaciones;
     private String descripcion;
     private String nombre;
     private Boolean estadoFinal;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private boolean activo;
     private Set<MpmTbitacoraCargoOnline> mpmTbitacoraCargoOnlines = new HashSet<MpmTbitacoraCargoOnline>(0);

    public MpmCestados() {
    }

	
    public MpmCestados(String idEstado, String descripcion, String creadoPor, Date fechaCreacion, String sistema, boolean activo) {
        this.idEstado = idEstado;
        this.descripcion = descripcion;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
        this.activo = activo;
    }
    public MpmCestados(String idEstado, MpmCnotificaciones mpmCnotificaciones, String descripcion, String nombre, Boolean estadoFinal, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, boolean activo, Set<MpmTbitacoraCargoOnline> mpmTbitacoraCargoOnlines) {
       this.idEstado = idEstado;
       this.mpmCnotificaciones = mpmCnotificaciones;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.estadoFinal = estadoFinal;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.mpmTbitacoraCargoOnlines = mpmTbitacoraCargoOnlines;
    }
   
    public String getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(String idEstado) {
        this.idEstado = idEstado;
    }
    public MpmCnotificaciones getMpmCnotificaciones() {
        return this.mpmCnotificaciones;
    }
    
    public void setMpmCnotificaciones(MpmCnotificaciones mpmCnotificaciones) {
        this.mpmCnotificaciones = mpmCnotificaciones;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Boolean getEstadoFinal() {
        return this.estadoFinal;
    }
    
    public void setEstadoFinal(Boolean estadoFinal) {
        this.estadoFinal = estadoFinal;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<MpmTbitacoraCargoOnline> getMpmTbitacoraCargoOnlines() {
        return this.mpmTbitacoraCargoOnlines;
    }
    
    public void setMpmTbitacoraCargoOnlines(Set<MpmTbitacoraCargoOnline> mpmTbitacoraCargoOnlines) {
        this.mpmTbitacoraCargoOnlines = mpmTbitacoraCargoOnlines;
    }




}


