package com.maxcom.mpm.model;
// Generated 18-sep-2014 9:04:00 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmCrespuestasCargos generated by hbm2java
 */
public class MpmCrespuestasCargos  implements java.io.Serializable {


     private String idRespuestaCargo;
     private MpmCtiposRespuestas mpmCtiposRespuestas;
     private String descripcion;
     private String origen;
     private boolean accionReintento;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private boolean activo;
     private Set<MpmTbitacoraCargoOnline> mpmTbitacoraCargoOnlines = new HashSet<MpmTbitacoraCargoOnline>(0);

    public MpmCrespuestasCargos() {
    }

	
    public MpmCrespuestasCargos(String idRespuestaCargo, MpmCtiposRespuestas mpmCtiposRespuestas, String descripcion, boolean accionReintento, String creadoPor, Date fechaCreacion, String sistema, boolean activo) {
        this.idRespuestaCargo = idRespuestaCargo;
        this.mpmCtiposRespuestas = mpmCtiposRespuestas;
        this.descripcion = descripcion;
        this.accionReintento = accionReintento;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
        this.activo = activo;
    }
    public MpmCrespuestasCargos(String idRespuestaCargo, MpmCtiposRespuestas mpmCtiposRespuestas, String descripcion, String origen, boolean accionReintento, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, boolean activo, Set<MpmTbitacoraCargoOnline> mpmTbitacoraCargoOnlines) {
       this.idRespuestaCargo = idRespuestaCargo;
       this.mpmCtiposRespuestas = mpmCtiposRespuestas;
       this.descripcion = descripcion;
       this.origen = origen;
       this.accionReintento = accionReintento;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.mpmTbitacoraCargoOnlines = mpmTbitacoraCargoOnlines;
    }
   
    public String getIdRespuestaCargo() {
        return this.idRespuestaCargo;
    }
    
    public void setIdRespuestaCargo(String idRespuestaCargo) {
        this.idRespuestaCargo = idRespuestaCargo;
    }
    public MpmCtiposRespuestas getMpmCtiposRespuestas() {
        return this.mpmCtiposRespuestas;
    }
    
    public void setMpmCtiposRespuestas(MpmCtiposRespuestas mpmCtiposRespuestas) {
        this.mpmCtiposRespuestas = mpmCtiposRespuestas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public boolean isAccionReintento() {
        return this.accionReintento;
    }
    
    public void setAccionReintento(boolean accionReintento) {
        this.accionReintento = accionReintento;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<MpmTbitacoraCargoOnline> getMpmTbitacoraCargoOnlines() {
        return this.mpmTbitacoraCargoOnlines;
    }
    
    public void setMpmTbitacoraCargoOnlines(Set<MpmTbitacoraCargoOnline> mpmTbitacoraCargoOnlines) {
        this.mpmTbitacoraCargoOnlines = mpmTbitacoraCargoOnlines;
    }




}


