package com.maxcom.mpm.model;
// Generated 23-sep-2014 23:46:54 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * MpmTbitacoraConsultaOnline generated by hbm2java
 */
public class MpmTbitacoraConsultaOnline  implements java.io.Serializable {


     private long idBitacoraConsulta;
     private String fechaCargo;
     private String referencia;
     private String idEstado;
     private String idRespuestaCargo;
     private String observaciones;
     private String banResultado;
     private String banNumeroAutorizacion;
     private String banNumeroOperacion;
     private String banMonto;
     private String banCdRespuesta;
     private String banNbRespuesta;
     private String creadoPor;
     private Date fechaCreacion;
     private String modificadoPor;
     private Date fechaModificacion;
     private String solicitudXml;
     private String respuestaXml;

    public MpmTbitacoraConsultaOnline() {
    }

	
    public MpmTbitacoraConsultaOnline(long idBitacoraConsulta, String idEstado, String creadoPor, Date fechaCreacion) {
        this.idBitacoraConsulta = idBitacoraConsulta;
        this.idEstado = idEstado;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
    }
    public MpmTbitacoraConsultaOnline(long idBitacoraConsulta, String fechaCargo, String referencia, String idEstado, String idRespuestaCargo, String observaciones, String banResultado, String banNumeroAutorizacion, String banNumeroOperacion, String banMonto, String banCdRespuesta, String banNbRespuesta, String creadoPor, Date fechaCreacion, String modificadoPor, Date fechaModificacion, String solicitudXml, String respuestaXml) {
       this.idBitacoraConsulta = idBitacoraConsulta;
       this.fechaCargo = fechaCargo;
       this.referencia = referencia;
       this.idEstado = idEstado;
       this.idRespuestaCargo = idRespuestaCargo;
       this.observaciones = observaciones;
       this.banResultado = banResultado;
       this.banNumeroAutorizacion = banNumeroAutorizacion;
       this.banNumeroOperacion = banNumeroOperacion;
       this.banMonto = banMonto;
       this.banCdRespuesta = banCdRespuesta;
       this.banNbRespuesta = banNbRespuesta;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.solicitudXml = solicitudXml;
       this.respuestaXml = respuestaXml;
    }
   
    public long getIdBitacoraConsulta() {
        return this.idBitacoraConsulta;
    }
    
    public void setIdBitacoraConsulta(long idBitacoraConsulta) {
        this.idBitacoraConsulta = idBitacoraConsulta;
    }
    public String getFechaCargo() {
        return this.fechaCargo;
    }
    
    public void setFechaCargo(String fechaCargo) {
        this.fechaCargo = fechaCargo;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(String idEstado) {
        this.idEstado = idEstado;
    }
    public String getIdRespuestaCargo() {
        return this.idRespuestaCargo;
    }
    
    public void setIdRespuestaCargo(String idRespuestaCargo) {
        this.idRespuestaCargo = idRespuestaCargo;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getBanResultado() {
        return this.banResultado;
    }
    
    public void setBanResultado(String banResultado) {
        this.banResultado = banResultado;
    }
    public String getBanNumeroAutorizacion() {
        return this.banNumeroAutorizacion;
    }
    
    public void setBanNumeroAutorizacion(String banNumeroAutorizacion) {
        this.banNumeroAutorizacion = banNumeroAutorizacion;
    }
    public String getBanNumeroOperacion() {
        return this.banNumeroOperacion;
    }
    
    public void setBanNumeroOperacion(String banNumeroOperacion) {
        this.banNumeroOperacion = banNumeroOperacion;
    }
    public String getBanMonto() {
        return this.banMonto;
    }
    
    public void setBanMonto(String banMonto) {
        this.banMonto = banMonto;
    }
    public String getBanCdRespuesta() {
        return this.banCdRespuesta;
    }
    
    public void setBanCdRespuesta(String banCdRespuesta) {
        this.banCdRespuesta = banCdRespuesta;
    }
    public String getBanNbRespuesta() {
        return this.banNbRespuesta;
    }
    
    public void setBanNbRespuesta(String banNbRespuesta) {
        this.banNbRespuesta = banNbRespuesta;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * @return the solicitudXml
     */
    public String getSolicitudXml() {
        return solicitudXml;
    }

    /**
     * @param solicitudXml the solicitudXml to set
     */
    public void setSolicitudXml(String solicitudXml) {
        this.solicitudXml = solicitudXml;
    }

    /**
     * @return the respuestaXml
     */
    public String getRespuestaXml() {
        return respuestaXml;
    }

    /**
     * @param respuestaXml the respuestaXml to set
     */
    public void setRespuestaXml(String respuestaXml) {
        this.respuestaXml = respuestaXml;
    }
    
}


