package com.maxcom.mpm.paypal.model;
// Generated 18-sep-2014 9:04:00 by Hibernate Tools 3.6.0



/**
 * MpmCusersWs generated by hbm2java
 */
public class MpmCusersWs  implements java.io.Serializable {


     private short id;
     private String userLogin;
     private String userPass;
     private String servicio;

    public MpmCusersWs() {
    }

    public MpmCusersWs(short id, String userLogin, String userPass, String servicio) {
       this.id = id;
       this.userLogin = userLogin;
       this.userPass = userPass;
       this.servicio = servicio;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }
    public String getServicio() {
        return this.servicio;
    }
    
    public void setServicio(String servicio) {
        this.servicio = servicio;
    }




}


