package com.maxcom.mpm.paypal.model;
// Generated 08-oct-2014 10:22:56 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmTbitacoraRecPaypal generated by hbm2java
 */
public class MpmTbitacoraRecPaypal  implements java.io.Serializable {
    
     private long idBitacoraRecPaypal;
     private String idTransaccion;
     private String referencia;
     private String token;
     private String respuesta;
     private String estatus;
     private String observaciones;
     private String tokenPaypal;
     private String estatusPaypal;
     private String idOperacionPaypal;
     private String fechaOperacionPaypal;
     private BigDecimal orderTotal;
     private Boolean tienePagoReferenciado;
     private String creadoPor;
     private String modificadoPor;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set<MpmTbitacoraRecPayerPaypal> mpmTbitacoraRecPayerPaypals = new HashSet<MpmTbitacoraRecPayerPaypal>(0);

    public MpmTbitacoraRecPaypal() {
    }

	
    public MpmTbitacoraRecPaypal(long idBitacoraRecPaypal, String creadoPor, Date fechaCreacion) {
        this.idBitacoraRecPaypal = idBitacoraRecPaypal;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
    }
    public MpmTbitacoraRecPaypal(long idBitacoraRecPaypal, String idTransaccion, String referencia, String token, String respuesta, String estatus, String observaciones, String tokenPaypal, String estatusPaypal, String idOperacionPaypal, String fechaOperacionPaypal, BigDecimal orderTotal, Boolean tienePagoReferenciado, String creadoPor, String modificadoPor, Date fechaCreacion, Date fechaModificacion, Set<MpmTbitacoraRecPayerPaypal> mpmTbitacoraRecPayerPaypals) {
       this.idBitacoraRecPaypal = idBitacoraRecPaypal;
       this.idTransaccion = idTransaccion;
       this.referencia = referencia;
       this.token = token;
       this.respuesta = respuesta;
       this.estatus = estatus;
       this.observaciones = observaciones;
       this.tokenPaypal = tokenPaypal;
       this.estatusPaypal = estatusPaypal;
       this.idOperacionPaypal = idOperacionPaypal;
       this.fechaOperacionPaypal = fechaOperacionPaypal;
       this.orderTotal = orderTotal;
       this.tienePagoReferenciado = tienePagoReferenciado;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.mpmTbitacoraRecPayerPaypals = mpmTbitacoraRecPayerPaypals;
    }
   
    public long getIdBitacoraRecPaypal() {
        return this.idBitacoraRecPaypal;
    }
    
    public void setIdBitacoraRecPaypal(long idBitacoraRecPaypal) {
        this.idBitacoraRecPaypal = idBitacoraRecPaypal;
    }
    public String getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(String idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getTokenPaypal() {
        return this.tokenPaypal;
    }
    
    public void setTokenPaypal(String tokenPaypal) {
        this.tokenPaypal = tokenPaypal;
    }
    public String getEstatusPaypal() {
        return this.estatusPaypal;
    }
    
    public void setEstatusPaypal(String estatusPaypal) {
        this.estatusPaypal = estatusPaypal;
    }
    public String getIdOperacionPaypal() {
        return this.idOperacionPaypal;
    }
    
    public void setIdOperacionPaypal(String idOperacionPaypal) {
        this.idOperacionPaypal = idOperacionPaypal;
    }
    public String getFechaOperacionPaypal() {
        return this.fechaOperacionPaypal;
    }
    
    public void setFechaOperacionPaypal(String fechaOperacionPaypal) {
        this.fechaOperacionPaypal = fechaOperacionPaypal;
    }
    public BigDecimal getOrderTotal() {
        return this.orderTotal;
    }
    
    public void setOrderTotal(BigDecimal orderTotal) {
        this.orderTotal = orderTotal;
    }
    public Boolean getTienePagoReferenciado() {
        return this.tienePagoReferenciado;
    }
    
    public void setTienePagoReferenciado(Boolean tienePagoReferenciado) {
        this.tienePagoReferenciado = tienePagoReferenciado;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<MpmTbitacoraRecPayerPaypal> getMpmTbitacoraRecPayerPaypals() {
        return this.mpmTbitacoraRecPayerPaypals;
    }
    
    public void setMpmTbitacoraRecPayerPaypals(Set<MpmTbitacoraRecPayerPaypal> mpmTbitacoraRecPayerPaypals) {
        this.mpmTbitacoraRecPayerPaypals = mpmTbitacoraRecPayerPaypals;
    }

    /**
     * @return the token
     */
    public String getToken() {
        return token;
    }

    /**
     * @param token the token to set
     */
    public void setToken(String token) {
        this.token = token;
    }




}


