package com.maxcom.mpm.paypal.model;
// Generated 06-oct-2014 23:27:32 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmTbitacoraSolPaypal generated by hbm2java
 */
public class MpmTbitacoraSolPaypal  implements java.io.Serializable {


     private long idBitacoraSolPaypal;
     private String idTransaccion;
     private String referencia;
     private String urlReturn;
     private String urlCancel;
     private Boolean referenciarPago;
     private String respuesta;
     private String estatus;
     private String observaciones;
     private String tokenPaypal;
     private String estatusPaypal;
     private String idOperacionPaypal;
     private String fechaOperacionPaypal;
     private String creadoPor;
     private String modificadoPor;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set<MpmTbitacoraDetaSolPaypal> mpmTbitacoraDetaSolPaypals = new HashSet<MpmTbitacoraDetaSolPaypal>(0);

    public MpmTbitacoraSolPaypal() {
    }

	
    public MpmTbitacoraSolPaypal(long idBitacoraSolPaypal, String creadoPor, Date fechaCreacion) {
        this.idBitacoraSolPaypal = idBitacoraSolPaypal;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
    }
    public MpmTbitacoraSolPaypal(long idBitacoraSolPaypal, String idTransaccion, String referencia, String urlReturn, String urlCancel, Boolean referenciarPago, String respuesta, String estatus, String observaciones, String tokenPaypal, String estatusPaypal, String idOperacionPaypal, String fechaOperacionPaypal, String creadoPor, String modificadoPor, Date fechaCreacion, Date fechaModificacion, Set<MpmTbitacoraDetaSolPaypal> mpmTbitacoraDetaSolPaypals) {
       this.idBitacoraSolPaypal = idBitacoraSolPaypal;
       this.idTransaccion = idTransaccion;
       this.referencia = referencia;
       this.urlReturn = urlReturn;
       this.urlCancel = urlCancel;
       this.referenciarPago = referenciarPago;
       this.respuesta = respuesta;
       this.estatus = estatus;
       this.observaciones = observaciones;
       this.tokenPaypal = tokenPaypal;
       this.estatusPaypal = estatusPaypal;
       this.idOperacionPaypal = idOperacionPaypal;
       this.fechaOperacionPaypal = fechaOperacionPaypal;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.mpmTbitacoraDetaSolPaypals = mpmTbitacoraDetaSolPaypals;
    }
   
    public long getIdBitacoraSolPaypal() {
        return this.idBitacoraSolPaypal;
    }
    
    public void setIdBitacoraSolPaypal(long idBitacoraSolPaypal) {
        this.idBitacoraSolPaypal = idBitacoraSolPaypal;
    }
    public String getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(String idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getUrlReturn() {
        return this.urlReturn;
    }
    
    public void setUrlReturn(String urlReturn) {
        this.urlReturn = urlReturn;
    }
    public String getUrlCancel() {
        return this.urlCancel;
    }
    
    public void setUrlCancel(String urlCancel) {
        this.urlCancel = urlCancel;
    }
    public Boolean getReferenciarPago() {
        return this.referenciarPago;
    }
    
    public void setReferenciarPago(Boolean referenciarPago) {
        this.referenciarPago = referenciarPago;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getTokenPaypal() {
        return this.tokenPaypal;
    }
    
    public void setTokenPaypal(String tokenPaypal) {
        this.tokenPaypal = tokenPaypal;
    }
    public String getEstatusPaypal() {
        return this.estatusPaypal;
    }
    
    public void setEstatusPaypal(String estatusPaypal) {
        this.estatusPaypal = estatusPaypal;
    }
    public String getIdOperacionPaypal() {
        return this.idOperacionPaypal;
    }
    
    public void setIdOperacionPaypal(String idOperacionPaypal) {
        this.idOperacionPaypal = idOperacionPaypal;
    }
    
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Serializable getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<MpmTbitacoraDetaSolPaypal> getMpmTbitacoraDetaSolPaypals() {
        return this.mpmTbitacoraDetaSolPaypals;
    }
    
    public void setMpmTbitacoraDetaSolPaypals(Set<MpmTbitacoraDetaSolPaypal> mpmTbitacoraDetaSolPaypals) {
        this.mpmTbitacoraDetaSolPaypals = mpmTbitacoraDetaSolPaypals;
    }

    /**
     * @return the fechaOperacionPaypal
     */
    public String getFechaOperacionPaypal() {
        return fechaOperacionPaypal;
    }

    /**
     * @param fechaOperacionPaypal the fechaOperacionPaypal to set
     */
    public void setFechaOperacionPaypal(String fechaOperacionPaypal) {
        this.fechaOperacionPaypal = fechaOperacionPaypal;
    }




}


