package com.maxcom.mpm.paypal.model;
// Generated 06-oct-2014 23:27:32 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * MpmTbitacoraDetaSolPaypal generated by hbm2java
 */
public class MpmTbitacoraDetaSolPaypal  implements java.io.Serializable {


     private long idBitacoraDetaSolPaypal;
     private MpmTbitacoraSolPaypal mpmTbitacoraSolPaypal;
     private Integer cantidad;
     private String descripcion;
     private BigDecimal precio;
     private String creadoPor;
     private String modificadoPor;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public MpmTbitacoraDetaSolPaypal() {
    }

	
    public MpmTbitacoraDetaSolPaypal(long idBitacoraDetaSolPaypal, String creadoPor, Date fechaCreacion) {
        this.idBitacoraDetaSolPaypal = idBitacoraDetaSolPaypal;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
    }
    public MpmTbitacoraDetaSolPaypal(long idBitacoraDetaSolPaypal, MpmTbitacoraSolPaypal mpmTbitacoraSolPaypal, Integer cantidad, String descripcion, BigDecimal precio, String creadoPor, String modificadoPor, Date fechaCreacion, Date fechaModificacion) {
       this.idBitacoraDetaSolPaypal = idBitacoraDetaSolPaypal;
       this.mpmTbitacoraSolPaypal = mpmTbitacoraSolPaypal;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
       this.precio = precio;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public long getIdBitacoraDetaSolPaypal() {
        return this.idBitacoraDetaSolPaypal;
    }
    
    public void setIdBitacoraDetaSolPaypal(long idBitacoraDetaSolPaypal) {
        this.idBitacoraDetaSolPaypal = idBitacoraDetaSolPaypal;
    }
    public MpmTbitacoraSolPaypal getMpmTbitacoraSolPaypal() {
        return this.mpmTbitacoraSolPaypal;
    }
    
    public void setMpmTbitacoraSolPaypal(MpmTbitacoraSolPaypal mpmTbitacoraSolPaypal) {
        this.mpmTbitacoraSolPaypal = mpmTbitacoraSolPaypal;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Serializable getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


