
package com.maxcom.mpm.paypal.client.paypal;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PayPalAPIInterfaceService", targetNamespace = "urn:ebay:api:PayPalAPI", wsdlLocation = "file:/C:/Documents%20and%20Settings/operador/Escritorio/wsimport/PayPalAPIInterfaceService.wsdl")
public class PayPalAPIInterfaceService
    extends Service
{

    private final static URL PAYPALAPIINTERFACESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.maxcom.mpm.paypal.client.paypal.PayPalAPIInterfaceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.maxcom.mpm.paypal.client.paypal.PayPalAPIInterfaceService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Documents%20and%20Settings/operador/Escritorio/wsimport/PayPalAPIInterfaceService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Documents%20and%20Settings/operador/Escritorio/wsimport/PayPalAPIInterfaceService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAYPALAPIINTERFACESERVICE_WSDL_LOCATION = url;
    }

    public PayPalAPIInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayPalAPIInterfaceService() {
        super(PAYPALAPIINTERFACESERVICE_WSDL_LOCATION, new QName("urn:ebay:api:PayPalAPI", "PayPalAPIInterfaceService"));
    }

    /**
     * 
     * @return
     *     returns PayPalAPIInterface
     */
    @WebEndpoint(name = "PayPalAPI")
    public PayPalAPIInterface getPayPalAPI() {
        return super.getPort(new QName("urn:ebay:api:PayPalAPI", "PayPalAPI"), PayPalAPIInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayPalAPIInterface
     */
    @WebEndpoint(name = "PayPalAPI")
    public PayPalAPIInterface getPayPalAPI(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ebay:api:PayPalAPI", "PayPalAPI"), PayPalAPIInterface.class, features);
    }

    /**
     * 
     * @return
     *     returns PayPalAPIAAInterface
     */
    @WebEndpoint(name = "PayPalAPIAA")
    public PayPalAPIAAInterface getPayPalAPIAA() {
        return super.getPort(new QName("urn:ebay:api:PayPalAPI", "PayPalAPIAA"), PayPalAPIAAInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayPalAPIAAInterface
     */
    @WebEndpoint(name = "PayPalAPIAA")
    public PayPalAPIAAInterface getPayPalAPIAA(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ebay:api:PayPalAPI", "PayPalAPIAA"), PayPalAPIAAInterface.class, features);
    }

}
