package com.maxcom.mpm.respuesta.dao;
// Generated 15-oct-2014 18:35:19 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * MpmDemoRespuestaSap generated by hbm2java
 */
public class MpmDemoRespuestaSap  implements java.io.Serializable {


     private long idSap;
     private long idCobranza;
     private String referencia;
     private String nombreCliente;
     private String cuenta;
     private BigDecimal importe;
     private String email;
     private boolean entidadFinanciera;
     private Long idTipoCuenta;
     private Long idMarcaTarjeta;
     private String idRespuestaCargo;
     private String observaciones;
     private String creadoPor;
     private String modificadoPor;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public MpmDemoRespuestaSap() {
    }

	
    public MpmDemoRespuestaSap(long idSap, long idCobranza, boolean entidadFinanciera, String creadoPor, Date fechaCreacion) {
        this.idSap = idSap;
        this.idCobranza = idCobranza;
        this.entidadFinanciera = entidadFinanciera;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
    }
    public MpmDemoRespuestaSap(long idSap, long idCobranza, String referencia, String nombreCliente, String cuenta, BigDecimal importe, String email, boolean entidadFinanciera, Long idTipoCuenta, Long idMarcaTarjeta, String idRespuestaCargo, String observaciones, String creadoPor, String modificadoPor, Date fechaCreacion, Date fechaModificacion) {
       this.idSap = idSap;
       this.idCobranza = idCobranza;
       this.referencia = referencia;
       this.nombreCliente = nombreCliente;
       this.cuenta = cuenta;
       this.importe = importe;
       this.email = email;
       this.entidadFinanciera = entidadFinanciera;
       this.idTipoCuenta = idTipoCuenta;
       this.idMarcaTarjeta = idMarcaTarjeta;
       this.idRespuestaCargo = idRespuestaCargo;
       this.observaciones = observaciones;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public long getIdSap() {
        return this.idSap;
    }
    
    public void setIdSap(long idSap) {
        this.idSap = idSap;
    }
    public long getIdCobranza() {
        return this.idCobranza;
    }
    
    public void setIdCobranza(long idCobranza) {
        this.idCobranza = idCobranza;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isEntidadFinanciera() {
        return this.entidadFinanciera;
    }
    
    public void setEntidadFinanciera(boolean entidadFinanciera) {
        this.entidadFinanciera = entidadFinanciera;
    }
    public Long getIdTipoCuenta() {
        return this.idTipoCuenta;
    }
    
    public void setIdTipoCuenta(Long idTipoCuenta) {
        this.idTipoCuenta = idTipoCuenta;
    }
    public Long getIdMarcaTarjeta() {
        return this.idMarcaTarjeta;
    }
    
    public void setIdMarcaTarjeta(Long idMarcaTarjeta) {
        this.idMarcaTarjeta = idMarcaTarjeta;
    }
    public String getIdRespuestaCargo() {
        return this.idRespuestaCargo;
    }
    
    public void setIdRespuestaCargo(String idRespuestaCargo) {
        this.idRespuestaCargo = idRespuestaCargo;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


