package com.maxcom.mpm.model;
// Generated 05-sep-2014 15:58:10 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmCtiposCuentas generated by hbm2java
 */
public class MpmCtiposCuentas  implements java.io.Serializable {


     private long idTipoCuenta;
     private MpmCgruposCobranza mpmCgruposCobranza;
     private String descripcion;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private boolean activo;
     private Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas = new HashSet<MpmTcobranzaSapDeta>(0);

    public MpmCtiposCuentas() {
    }

	
    public MpmCtiposCuentas(long idTipoCuenta, MpmCgruposCobranza mpmCgruposCobranza, String descripcion, String creadoPor, Date fechaCreacion, String sistema, boolean activo) {
        this.idTipoCuenta = idTipoCuenta;
        this.mpmCgruposCobranza = mpmCgruposCobranza;
        this.descripcion = descripcion;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
        this.activo = activo;
    }
    public MpmCtiposCuentas(long idTipoCuenta, MpmCgruposCobranza mpmCgruposCobranza, String descripcion, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, boolean activo, Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas) {
       this.idTipoCuenta = idTipoCuenta;
       this.mpmCgruposCobranza = mpmCgruposCobranza;
       this.descripcion = descripcion;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.mpmTcobranzaSapDetas = mpmTcobranzaSapDetas;
    }
   
    public long getIdTipoCuenta() {
        return this.idTipoCuenta;
    }
    
    public void setIdTipoCuenta(long idTipoCuenta) {
        this.idTipoCuenta = idTipoCuenta;
    }
    public MpmCgruposCobranza getMpmCgruposCobranza() {
        return this.mpmCgruposCobranza;
    }
    
    public void setMpmCgruposCobranza(MpmCgruposCobranza mpmCgruposCobranza) {
        this.mpmCgruposCobranza = mpmCgruposCobranza;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<MpmTcobranzaSapDeta> getMpmTcobranzaSapDetas() {
        return this.mpmTcobranzaSapDetas;
    }
    
    public void setMpmTcobranzaSapDetas(Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas) {
        this.mpmTcobranzaSapDetas = mpmTcobranzaSapDetas;
    }




}


