package com.maxcom.mpm.model;
// Generated 05-sep-2014 15:58:10 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmCgruposCobranza generated by hbm2java
 */
public class MpmCgruposCobranza  implements java.io.Serializable {


     private long idGrupoCobranza;
     private String descripcion;
     private String nombreCorto;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private boolean activo;
     private Set<MpmCmarcasTarjetas> mpmCmarcasTarjetases = new HashSet<MpmCmarcasTarjetas>(0);
     private Set<MpmCtiposCuentas> mpmCtiposCuentases = new HashSet<MpmCtiposCuentas>(0);

    public MpmCgruposCobranza() {
    }

	
    public MpmCgruposCobranza(long idGrupoCobranza, String descripcion, String nombreCorto, String creadoPor, Date fechaCreacion, String sistema, boolean activo) {
        this.idGrupoCobranza = idGrupoCobranza;
        this.descripcion = descripcion;
        this.nombreCorto = nombreCorto;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
        this.activo = activo;
    }
    public MpmCgruposCobranza(long idGrupoCobranza, String descripcion, String nombreCorto, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, boolean activo, Set<MpmCmarcasTarjetas> mpmCmarcasTarjetases, Set<MpmCtiposCuentas> mpmCtiposCuentases) {
       this.idGrupoCobranza = idGrupoCobranza;
       this.descripcion = descripcion;
       this.nombreCorto = nombreCorto;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.mpmCmarcasTarjetases = mpmCmarcasTarjetases;
       this.mpmCtiposCuentases = mpmCtiposCuentases;
    }
   
    public long getIdGrupoCobranza() {
        return this.idGrupoCobranza;
    }
    
    public void setIdGrupoCobranza(long idGrupoCobranza) {
        this.idGrupoCobranza = idGrupoCobranza;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<MpmCmarcasTarjetas> getMpmCmarcasTarjetases() {
        return this.mpmCmarcasTarjetases;
    }
    
    public void setMpmCmarcasTarjetases(Set<MpmCmarcasTarjetas> mpmCmarcasTarjetases) {
        this.mpmCmarcasTarjetases = mpmCmarcasTarjetases;
    }
    public Set<MpmCtiposCuentas> getMpmCtiposCuentases() {
        return this.mpmCtiposCuentases;
    }
    
    public void setMpmCtiposCuentases(Set<MpmCtiposCuentas> mpmCtiposCuentases) {
        this.mpmCtiposCuentases = mpmCtiposCuentases;
    }




}


