package com.maxcom.mpm.model;
// Generated 05-sep-2014 15:58:10 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmTcobranzaSap generated by hbm2java
 */
public class MpmTcobranzaSap  implements java.io.Serializable {


     private long idCobranza;
     private MpmCestados mpmCestados;
     private String producto;
     private String componente;
     private String periodo;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private String idsap;
     private String observaciones;
     private Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas = new HashSet<MpmTcobranzaSapDeta>(0);

    public MpmTcobranzaSap() {
    }

	
    public MpmTcobranzaSap(long idCobranza, MpmCestados mpmCestados, String producto, String componente, String periodo, String creadoPor, Date fechaCreacion, String sistema, String idsap) {
        this.idCobranza = idCobranza;
        this.mpmCestados = mpmCestados;
        this.producto = producto;
        this.componente = componente;
        this.periodo = periodo;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
        this.idsap = idsap;
    }
    public MpmTcobranzaSap(long idCobranza, MpmCestados mpmCestados, String producto, String componente, String periodo, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, String idsap, String observaciones, Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas) {
       this.idCobranza = idCobranza;
       this.mpmCestados = mpmCestados;
       this.producto = producto;
       this.componente = componente;
       this.periodo = periodo;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.idsap = idsap;
       this.observaciones = observaciones;
       this.mpmTcobranzaSapDetas = mpmTcobranzaSapDetas;
    }
   
    public long getIdCobranza() {
        return this.idCobranza;
    }
    
    public void setIdCobranza(long idCobranza) {
        this.idCobranza = idCobranza;
    }
    public MpmCestados getMpmCestados() {
        return this.mpmCestados;
    }
    
    public void setMpmCestados(MpmCestados mpmCestados) {
        this.mpmCestados = mpmCestados;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public String getComponente() {
        return this.componente;
    }
    
    public void setComponente(String componente) {
        this.componente = componente;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getIdsap() {
        return this.idsap;
    }
    
    public void setIdsap(String idsap) {
        this.idsap = idsap;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<MpmTcobranzaSapDeta> getMpmTcobranzaSapDetas() {
        return this.mpmTcobranzaSapDetas;
    }
    
    public void setMpmTcobranzaSapDetas(Set<MpmTcobranzaSapDeta> mpmTcobranzaSapDetas) {
        this.mpmTcobranzaSapDetas = mpmTcobranzaSapDetas;
    }




}


