package com.maxcom.mpm.model;
// Generated 05-sep-2014 15:58:10 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MpmTprocesos generated by hbm2java
 */
public class MpmTprocesos  implements java.io.Serializable {


     private long idProceso;
     private MpmCestados mpmCestados;
     private String tipoProceso;
     private Date fechaIniGen;
     private Date fechaCierre;
     private String creadoPor;
     private Date fechaCreacion;
     private String sistema;
     private String modificadoPor;
     private Date fechaModificacion;
     private Date fechaFinGen;
     private Set<MpmTlotesCargoAutomatico> mpmTlotesCargoAutomaticos = new HashSet<MpmTlotesCargoAutomatico>(0);

    public MpmTprocesos() {
    }

	
    public MpmTprocesos(long idProceso, MpmCestados mpmCestados, String tipoProceso, Date fechaIniGen, String creadoPor, Date fechaCreacion, String sistema) {
        this.idProceso = idProceso;
        this.mpmCestados = mpmCestados;
        this.tipoProceso = tipoProceso;
        this.fechaIniGen = fechaIniGen;
        this.creadoPor = creadoPor;
        this.fechaCreacion = fechaCreacion;
        this.sistema = sistema;
    }
    public MpmTprocesos(long idProceso, MpmCestados mpmCestados, String tipoProceso, Date fechaIniGen, Date fechaCierre, String creadoPor, Date fechaCreacion, String sistema, String modificadoPor, Date fechaModificacion, Date fechaFinGen, Set<MpmTlotesCargoAutomatico> mpmTlotesCargoAutomaticos) {
       this.idProceso = idProceso;
       this.mpmCestados = mpmCestados;
       this.tipoProceso = tipoProceso;
       this.fechaIniGen = fechaIniGen;
       this.fechaCierre = fechaCierre;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
       this.sistema = sistema;
       this.modificadoPor = modificadoPor;
       this.fechaModificacion = fechaModificacion;
       this.fechaFinGen = fechaFinGen;
       this.mpmTlotesCargoAutomaticos = mpmTlotesCargoAutomaticos;
    }
   
    public long getIdProceso() {
        return this.idProceso;
    }
    
    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }
    public MpmCestados getMpmCestados() {
        return this.mpmCestados;
    }
    
    public void setMpmCestados(MpmCestados mpmCestados) {
        this.mpmCestados = mpmCestados;
    }
    public String getTipoProceso() {
        return this.tipoProceso;
    }
    
    public void setTipoProceso(String tipoProceso) {
        this.tipoProceso = tipoProceso;
    }
    public Date getFechaIniGen() {
        return this.fechaIniGen;
    }
    
    public void setFechaIniGen(Date fechaIniGen) {
        this.fechaIniGen = fechaIniGen;
    }
    public Date getFechaCierre() {
        return this.fechaCierre;
    }
    
    public void setFechaCierre(Date fechaCierre) {
        this.fechaCierre = fechaCierre;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Date getFechaFinGen() {
        return this.fechaFinGen;
    }
    
    public void setFechaFinGen(Date fechaFinGen) {
        this.fechaFinGen = fechaFinGen;
    }
    public Set<MpmTlotesCargoAutomatico> getMpmTlotesCargoAutomaticos() {
        return this.mpmTlotesCargoAutomaticos;
    }
    
    public void setMpmTlotesCargoAutomaticos(Set<MpmTlotesCargoAutomatico> mpmTlotesCargoAutomaticos) {
        this.mpmTlotesCargoAutomaticos = mpmTlotesCargoAutomaticos;
    }




}


